### ISSUE TITLE
SendPdu -  Thread Aborted error - Please help.

### ISSUE THREAD

**Issue by poonamkumariasp** [AdhamAwadhi/JamaaSMPP#26]
Hi Adham,

I am sending acknowledgement of receipt of message delivery notification using following code, inside client_MessageDelivered event:

**PDUHeader header = new PDUHeader(CommandType.DeliverSmResp, seqNumber, SmppErrorCode.ESME_ROK, (uint)seqNumber.ToString().Length);
DeliverSm ackPDU = new DeliverSm(header, client.SmppEncodingService);
var resp = client.SendPdu(ackPDU, 0);**

But I am getting thread aborted error at **client.SendPdu(ackPDU, 0);**

Following is the stack trace, please let me know if i am doing it all wrong or what:

 at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at JamaaTech.Smpp.Net.Lib.PDUWaitContext.WaitForAlert() in D:\Work\My\JamaaSMPP\JamaaTech.SMPP.Net.Lib\PDUWaitContext.cs:line 57
   at JamaaTech.Smpp.Net.Lib.ResponseHandler.WaitResponse(RequestPDU pdu, Int32 timeOut) in D:\Work\My\JamaaSMPP\JamaaTech.SMPP.Net.Lib\ResponseHandler.cs:line 97
   at JamaaTech.Smpp.Net.Lib.SmppClientSession.SendPdu(RequestPDU pdu, Int32 timeout) in D:\Work\My\JamaaSMPP\JamaaTech.SMPP.Net.Lib\SmppClientSession.cs:line 172
   at JamaaTech.Smpp.Net.Client.SmppClient.SendPdu(RequestPDU pdu, Int32 timeout) in D:\Work\My\JamaaSMPP\JamaaTech.Smpp.Net.Client\SmppClient.cs:line 216
   at SSD.SMPPLib.SMPPClass.client_MessageDelivered(Object sender, MessageEventArgs e) in C:\Source\SSD.SMPPLib31Oct2018\SSD.SMPPLib\SSD.SMPPLib\SMPPClass.cs:line 487

**Comment by AdhamAwadhi** [comment]
Because you set **Timeout** to **0** in **client.SendPdu(ackPDU, 0);**
You can use `DefaultResponseTimeout = 5000` or set it as needed as you see
