### ISSUE TITLE
Sending Bulk SMS

### ISSUE THREAD

**Issue by SasankaM** [AdhamAwadhi/JamaaSMPP#42]
We are using your JamaaSMPP library in one of our projects and it is really useful and helpful. Could you please clarify the below query?

1)	Does the library supports bulk SMS, meaning can we send multiple mobile numbers at the same time with some delimiter?
2)	If yes, could you please let us know how this can be achieved.

When we try to send the list of mobile numbers, we get below Error code

at JamaaTech.Smpp.Net.Client.SmppClient.SendPdu(RequestPDU pdu, Int32 timeout) in D:\Work\My\JamaaSMPP\JamaaTech.Smpp.Net.Client\SmppClient.cs:line 218
at JamaaTech.Smpp.Net.Client.SmppClient.SendMessage(ShortMessage message, Int32 timeOut) in D:\Work\My\JamaaSMPP\JamaaTech.Smpp.Net.Client\SmppClient.cs:line 19
and smppEx.ErrorCode - 1078

Regards,
Sasanka M

**Comment by mayurrrathod** [comment]
No, you can not send it on bulk. You have to use for loop based on your language.
