### ISSUE TITLE
NULL Reference Exception on Continual Connection Error

### ISSUE THREAD

**Issue by danielckelly** [AdhamAwadhi/JamaaSMPP#47]
Hi,
If you enter the wrong SMPP details or there are continual connection issues, eventually (usually within 10 minutes) you get an exception that crashes the entire application (no just the SMPP client) as we have everything wrapped around a Try / Catch Block and the exception does not get thrown back to the calling method.

Source is JamaaTech.Smpp.Net.Lib

The exception Stack Trace is as follows:-

   at JamaaTech.Smpp.Net.Lib.StreamParser.RaiseParserExceptionEvent(Exception exception)
   at JamaaTech.Smpp.Net.Lib.StreamParser.HandleException(Exception ex)
   at JamaaTech.Smpp.Net.Lib.StreamParser.WaitPDU()
   at JamaaTech.Smpp.Net.Lib.StreamParser.RunNow()
   at JamaaTech.Smpp.Net.Lib.Util.RunningComponent.ThreadCallback()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

And Excedption Details:-

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=JamaaTech.Smpp.Net.Lib
  StackTrace:
       at JamaaTech.Smpp.Net.Lib.StreamParser.RaiseParserExceptionEvent(Exception exception)
       at JamaaTech.Smpp.Net.Lib.StreamParser.HandleException(Exception ex)
       at JamaaTech.Smpp.Net.Lib.StreamParser.WaitPDU()
       at JamaaTech.Smpp.Net.Lib.StreamParser.RunNow()
       at JamaaTech.Smpp.Net.Lib.Util.RunningComponent.ThreadCallback()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Thanks,

Daniel.

**Comment by danielckelly** [comment]
Upon loading the source, visual studio is breaking inside StreamParser.cs - Line 112 (inside Method RunNow()) which has a Single Throw Statement on it ( http://btg.io/dk/JamaaException.png )
